- id: wled_speed
  alias: wled_speed
  trigger:
  - entity_id: input_number.ledspeed
    platform: state
  condition: []
  action:
  - data_template:
      topic: wled/all/api
      payload: SX={{ states('input_number.ledspeed') | int }}
    service: mqtt.publish
- id: wled_intensity
  alias: wled_intensity
  trigger:
  - entity_id: input_number.ledintensity
    platform: state
  condition: []
  action:
  - data_template:
      topic: wled/all/api
      payload: IX={{ states('input_number.ledintensity') | int }}
    service: mqtt.publish
- id: wled_palette
  alias: WLED Palette
  trigger:
  - platform: state
    entity_id: input_select.wled_palette_list
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: wled/all/api
      payload: '{{ states(''input_select.wled_palette_list'') }}'
- id: wled_presets
  alias: WLED Presets
  trigger:
  - platform: state
    entity_id: input_select.wled_presets
  condition: []
  action:
  - service: mqtt.publish
    data_template:
      topic: wled/all/api
      payload: '{{ states(''input_select.wled_presets'') }}'
- id: 5326fdd5087a4adcb7758366a55fcbe5
  alias: MiLight Forwarder
  trigger:
  - platform: mqtt
    topic: milight/updates/0x1A75/rgb_cct/+
  action:
  - service: mqtt.publish
    data_template:
      topic: milight/commands/0x1B75/rgb_cct/{{ trigger.topic.split('/')[4] }}
      payload_template: '{{ trigger.payload }}

        '
  initial_state: true
  mode: queued
  max: 10
- alias: MilightAll
  initial_state: true
  trigger:
    platform: mqtt
    topic: milight/updates/0x1A75/rgb_cct/0
  action:
  - service: mqtt.publish
    data_template:
      topic: milight/commands/0x1B75/rgb_cct/1
      payload_template: '{{ trigger.payload }}

        '
  - service: mqtt.publish
    data_template:
      topic: milight/commands/0x1B75/rgb_cct/2
      payload_template: '{{ trigger.payload }}

        '
  - service: mqtt.publish
    data_template:
      topic: milight/commands/0x1B75/rgb_cct/3
      payload_template: '{{ trigger.payload }}

        '
  - service: mqtt.publish
    data_template:
      topic: milight/commands/0x1B75/rgb_cct/4
      payload_template: '{{ trigger.payload }}

        '
  id: bfba1df920894ffaa8525d3147c854ed
- alias: MiLight Wall Remote
  initial_state: true
  trigger:
    platform: mqtt
    topic: milight/updates/0x6B5F/rgb_cct/+
  action:
  - service: mqtt.publish
    data_template:
      topic: milight/commands/0x1B75/rgb_cct/{{ trigger.topic.split('/')[4] }}
      payload_template: '{{ trigger.payload }}

        '
  id: e51a5125247145c697190b3470a4e586
- alias: MilightWallAll
  initial_state: true
  trigger:
    platform: mqtt
    topic: milight/updates/0x6B5F/rgb_cct/0
  action:
  - service: mqtt.publish
    data_template:
      topic: milight/commands/0x1B75/rgb_cct/1
      payload_template: '{{ trigger.payload }}

        '
  - service: mqtt.publish
    data_template:
      topic: milight/commands/0x1B75/rgb_cct/2
      payload_template: '{{ trigger.payload }}

        '
  - service: mqtt.publish
    data_template:
      topic: milight/commands/0x1B75/rgb_cct/3
      payload_template: '{{ trigger.payload }}

        '
  - service: mqtt.publish
    data_template:
      topic: milight/commands/0x1B75/rgb_cct/4
      payload_template: '{{ trigger.payload }}

        '
  id: 4eb35eae47854330b973a335d33409e5
- id: 82c98f55cc1e4c0aa676c7921d3845cb
  alias: Wake me up with bedroom light transition for weekdays
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.wakeup_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: input_boolean.wakeup_enabled
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup_weekend
      state: 'on'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - data:
      brightness: 255
      transition: 600
    entity_id: light.milightsselect
    service: light.turn_on
  mode: single
- id: '1590187741446'
  alias: Climate Fan On
  description: ''
  trigger:
  - above: '24'
    entity_id: sensor.bedroom_temprature
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_boolean.climate_overide
    state: 'off'
  action:
  - data: {}
    entity_id: switch.big_fan
    service: switch.turn_on
- id: '1590272486976'
  alias: 'Climate Test Off '
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /10
  condition:
  - condition: and
    conditions:
    - below: '25'
      condition: numeric_state
      entity_id: sensor.bedroom_temprature
    - condition: state
      entity_id: input_boolean.climate_overide
      state: 'on'
    - condition: state
      entity_id: switch.big_fan
      state: 'on'
  action:
  - data: {}
    entity_id: switch.big_fan
    service: switch.turn_off
- id: '1590272706870'
  alias: Climate Test On
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /30
  condition:
  - condition: and
    conditions:
    - above: '25'
      condition: numeric_state
      entity_id: sensor.bedroom_temprature
    - condition: state
      entity_id: input_boolean.climate_overide
      state: 'on'
  action:
  - data: {}
    entity_id: switch.big_fan
    service: switch.turn_on
- id: '1595783626201'
  alias: PS4 Audio Switcher
  description: ''
  trigger:
  - entity_id: media_player.playstation_4
    from: idle
    platform: state
    to: 'playing '
  - entity_id: media_player.playstation_4
    from: standby
    platform: state
    to: playing
  condition: []
  action:
  - data:
      entity_id: switch.ps4_audio
    entity_id: switch.ps4_audio
    service: switch.turn_on
  mode: single
- id: '1595784064306'
  alias: TV Audio Switcher
  description: ''
  trigger:
  - entity_id: media_player.playstation_4
    from: Playing
    platform: state
    to: Standby
  condition: []
  action:
  - data: {}
    entity_id: switch.ps4audio
    service: switch.turn_off
  mode: single
- id: '1597163776632'
  alias: Temprature Stable Off
  description: ''
  trigger:
  - entity_id: binary_sensor.temp_rising
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.temp_falling
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.temprature_stable
    service: input_boolean.turn_off
  mode: single
- id: '1597187359729'
  alias: stable off
  description: ''
  trigger:
  - platform: time_pattern
    seconds: '30'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.temp_falling
      state: 'on'
    - condition: state
      entity_id: binary_sensor.temp_rising
      state: 'on'
  action:
  - data: {}
    entity_id: input_boolean.temprature_stable
    service: input_boolean.turn_off
  mode: single
- id: '1597187362134'
  alias: stable off
  description: ''
  trigger:
  - platform: time_pattern
    seconds: '30'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.temp_falling
      state: 'on'
    - condition: state
      entity_id: binary_sensor.temp_rising
      state: 'on'
  action:
  - data: {}
    entity_id: input_boolean.temprature_stable
    service: input_boolean.turn_off
  mode: single
- id: '1597277741425'
  alias: Temp Rising Notify Pixel 5
  description: ''
  trigger:
  - entity_id: binary_sensor.temp_rising
    for: '60'
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '10:00'
    before: 03:00
    condition: time
  action:
  - data:
      data:
        group: heat
      message: Bedroom Temprature {{ states.sensor.bedroom_temprature.state}}
      title: Temprature Rising
    service: notify.mobile_app_pixel_5
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  mode: single
- id: '1597368073343'
  alias: Temprature Stable On
  description: ''
  trigger:
  - entity_id: binary_sensor.temp_rising
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.temp_falling
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.temprature_stable
    service: input_boolean.turn_on
  mode: single
- id: '1597518848457'
  alias: Set Dark Theme At Night
  description: ''
  trigger:
  - entity_id: sun.sun
    from: above_horizon
    platform: state
    to: below
  condition: []
  action:
  - data:
      mode: dark
      name: default
    service: frontend.set_theme
  mode: single
- id: '1597519480958'
  alias: Set Light Theme At Wakeup Time
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.wakeup_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition: []
  action:
  - data:
      mode: light
    service: frontend.set_theme
  mode: single
- id: '1597599054013'
  alias: Qbit Active
  description: ''
  trigger:
  - entity_id: sensor.qbittorrent_status
    from: idle
    platform: state
    to: up_down
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.qbit_active
    service: input_boolean.turn_on
  mode: single
- id: '1602270151909'
  alias: Outdoor Lighting
  description: Turn the outdoor lights on 1 hour before sunset
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.outdoor_lights
  mode: single
- id: '1602283388216'
  alias: Outdoor Lighting Off
  description: Turn Outdoor Lights Off at 12
  trigger:
  - platform: time
    at: input_datetime.turn_off_outdoor_lights
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.outdoor_lights
  mode: single
- id: '1604772807889'
  alias: 'PS4 Test '
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.playstation_4
    from: 'Idle '
    to: 'Playing '
  - platform: state
    entity_id: media_player.playstation_4
    from: 'Standby '
    to: 'Playing '
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.ps4_audio
  mode: single
- id: '1605294470514'
  alias: switcher2
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.playstation_4
    from: standby
    to: playing
  - platform: state
    entity_id: media_player.playstation_4
    from: idle
    to: playing
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.ps4_audio
  mode: single
- id: '1605294585768'
  alias: switcher1
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.playstation_4
    from: playing
    to: standby
  - platform: state
    entity_id: media_player.playstation_4
    from: idle
    to: standby
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.ps4_audio
  mode: single
- id: '1606745772893'
  alias: Tag Test Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: c639f5ee-61a1-42af-85a8-b68b96e858a0
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.slow_fade
  mode: single
- id: '1606746502620'
  alias: Tag Test Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: c639f5ee-61a1-42af-85a8-b68b96e858a0
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.slow_fade
  mode: single
- id: '1606746503964'
  alias: Tag Test Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: c639f5ee-61a1-42af-85a8-b68b96e858a0
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.slow_fade
  mode: single
- id: '1606761018142'
  alias: Tag Test Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: c639f5ee-61a1-42af-85a8-b68b96e858a0
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.slow_fade
  mode: single
- id: '1606761019158'
  alias: Tag Test Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: c639f5ee-61a1-42af-85a8-b68b96e858a0
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.slow_fade
  mode: single
- id: '1609437036805'
  alias: Tag Door Pause is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 6fa8f3c6-55af-42ba-a5c9-066b27cf8b6d
  condition: []
  action:
  - service: media_player.media_play_pause
    data: {}
    entity_id: media_player.kodi
  mode: single
- id: '1618535853663'
  alias: Tag Fade Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 2299bdda-0b04-465e-9dd0-0be6b1acfdd4
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.slow_fade
  mode: single
- id: '1618535929860'
  alias: Tag Fade Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 2299bdda-0b04-465e-9dd0-0be6b1acfdd4
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.slow_fade
  mode: single
- id: '1618535931748'
  alias: Tag Fade Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 2299bdda-0b04-465e-9dd0-0be6b1acfdd4
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.slow_fade
  mode: single
- id: '1627678821676'
  alias: Input is rainbow bass ledfx
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.ledfx_scene
  condition:
  - condition: state
    entity_id: input_select.ledfx_scene
    state: Rainbow Bass
  action:
  - service: script.ledfx_rainbow
  mode: single
- id: '1627678918582'
  alias: Input is Orange
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.ledfx_scene
  condition:
  - condition: state
    entity_id: input_select.ledfx_scene
    state: Orange
  action:
  - service: script.ledfx_orange
  mode: single
- id: '1627682012790'
  alias: Input is off
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.ledfx_scene
  condition:
  - condition: state
    entity_id: input_select.ledfx_scene
    state: 'Off'
  action:
  - service: shell_command.ledfxnoeffect
  mode: single
