
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
homekit: !include homekit.yaml
#Core Platforms
discovery:
wake_on_lan:
logger:
  default: info
  logs:
    custom_components.prismatik: debug
    homeassistant.components.media_player: debug
    custom_components.ledfxrm: debug
tts:
  - platform: google_translate
history: 
  include:
    entities: !include history.yaml
frontend:
  themes: !include_dir_merge_named themes
cloud:
  google_actions: !include homekit.yaml
#Binary Sensors
binary_sensor:
  - platform: trend
    sensors:
      temp_falling:
        entity_id: sensor.bedroom_temprature
        sample_duration: 300
        max_samples: 60
        min_gradient: -0.0008
        device_class: cold
        friendly_name: "Temprature Falling"

      temp_rising:
        entity_id: sensor.bedroom_temprature
        sample_duration: 300
        max_samples: 60
        min_gradient: 0.0008
        device_class: heat
        friendly_name: "Temprarture Rising"
#Weather
weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

#Media Players
webostv:
    host: 192.168.0.14
notify: 
  - platform: kodi
    name: kodi
    host: 192.168.0.56
    username: kodi
    password: cam
    
panel_iframe:
  kodi:
    title: 'Kodi'
    url: 'http://192.168.1.56:8080'
    icon: mdi:kodi
#Lights
light:
 # - platform: prismatik
  #  host: 192.168.0.15
   # port: 7123
  - platform: group
    name: Milights
    entities:
      - light.bedside
      - light.top
      - light.lamp
      - light.unit
      - light.front 
  - platform: group
    name: milightsselect
    entities: 
      - light.lamp
      - light.unit
      - light.front
  - platform: limitlessled
    bridges: 
      - host: 192.168.0.3
        groups: 
        - number: 1
          type: bridge-led
          name: Bedside
#Inputs
input_select:
  wled_presets:
    options: !include presets.yaml
  wled_palette_list:
    options: !include palettes.yaml
input_number:
  ledspeed:
    name: Speed
    initial: 0
    min: 0
    max: 255
    step: 1
  ledintensity:
    name: Intensity
    initial: 0
    min: 0
    max: 255
    step: 1
input_boolean :
  wakeup_enabled:
    name: "Wake-up lights"
    initial: off
    icon: mdi:theme-light-dark
  wakeup_weekend:
    name: "Enable Wake-up on weekends"
    initial: off # I disable the system on default on weekends
    icon: mdi:calendar-blank
input_datetime:
  wakeup_time:
    name: "Start lights at"
    has_time: true
    has_date: false
input_text:
  announce_kodi:
    name: Announce Kodi
    initial: Message To Speak
#LedFX Shell Commands    
shell_command: 
    ledfxrainbow: curl -L -X PUT 'http://192.168.1.56:8888/api/scenes' --data-raw '{"id":"bass","action":"activate"}'
    ledfxorange: curl -L -X PUT 'http://192.168.1.56:8888/api/scenes' --data-raw '{"id":"orange","action":"activate"}'
    ledfxnoeffect: curl -L -X DELETE 'http://192.168.1.56:8888/api/devices/wled/effects'
