
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# Sensors 
sensor:
  - platform: sonarr
    api_key: secret
    host: 192.168.0.15
    monitored_conditions:
      - upcoming
    days: 2
  - platform: waqi
    token: secret
    locations:
      - camden
  - platform: sonarr_upcoming_media
    api_key: secret
    host: 192.168.0.15
    port: 8989
    days: 7
    max: 10
  - platform: qbittorrent
    url: 'http://192.168.0.15:9091'
    username: secret
    password: secret
  - platform: dht
    sensor: DHT11
    pin: 4
    monitored_conditions:
    - temperature
    - humidity
  - platform: moon
  - platform: london_underground
    line:
      - Northern
      - London Overground
  - platform: template
    sensors:
        pm2_5:
            value_template: "{{ states.sensor.waqi_camden_euston_road_united_kingdom.attributes.pm_2_5 }}"
            friendly_name: "PM 2.5"
            unit_of_measurement: AQI
        pm10:
            value_template: "{{ states.sensor.waqi_camden_euston_road_united_kingdom.attributes.pm_10 }}"
            friendly_name: "PM10"
            unit_of_measurement: AQI
        n02:
            value_template: "{{ states.sensor.waqi_camden_euston_road_united_kingdom.attributes.nitrogen_dioxide }}"
            friendly_name: "Nitrogen Dioxide"
            unit_of_measurement: AQI
  - platform: time_date
    display_options:
      - 'time'
#Weather
weather:
  - platform: darksky
    api_key: secret
    mode: daily

#Discovery
discovery:
#Media Players
media_player:
  - platform: kodi
    host: 192.168.0.15
    username: secret
    password: secret
#Switches
switch: !include switches.yaml
#Lights
light:
  - platform: group
    name: Milights
    entities:
      - light.bedside
      - light.top
      - light.lamp
      - light.unit
      - light.front 
  - platform: group
    name: milightsselect
    entities: 
      - light.lamp
      - light.unit
      - light.front
  - platform: mqtt
    name: "WLED Lights"
    command_topic: "wled/all"
    brightness_command_topic: "wled/all"
    rgb_command_topic: "wled/all/col"
    rgb_command_template: "{{ '#%02x%02x%02x' | format(red, green, blue)}}"
    effect_list:
    - "[FX=00] Solid"
    - "[FX=01] Blink"
    - "[FX=02] Breathe"
    - "[FX=03] Wipe"
    - "[FX=04] Wipe Random"
    - "[FX=05] Random Colors"
    - "[FX=06] Sweep"
    - "[FX=07] Dynamic"
    - "[FX=08] Colorloop"
    - "[FX=09] Rainbow"
    - "[FX=10] Scan"
    - "[FX=11] Dual Scan"
    - "[FX=12] Fade"
    - "[FX=13] Chase"
    - "[FX=14] Chase Rainbow"
    - "[FX=15] Running"
    - "[FX=16] Saw"
    - "[FX=17] Twinkle"
    - "[FX=18] Dissolve"
    - "[FX=19] Dissolve Rnd"
    - "[FX=20] Sparkle"
    - "[FX=21] Dark Sparkle"
    - "[FX=22] Sparkle+"
    - "[FX=23] Strobe"
    - "[FX=24] Strobe Rainbow"
    - "[FX=25] Mega Strobe"
    - "[FX=26] Blink Rainbow"
    - "[FX=27] Android"
    - "[FX=28] Chase"
    - "[FX=29] Chase Random"
    - "[FX=30] Chase Rainbow"
    - "[FX=31] Chase Flash"
    - "[FX=32] Chase Flash Rnd"
    - "[FX=33] Rainbow Runner"
    - "[FX=34] Colorful"
    - "[FX=35] Traffic Light"
    - "[FX=36] Sweep Random"
    - "[FX=37] Running 2"
    - "[FX=38] Red & Blue"
    - "[FX=39] Stream"
    - "[FX=40] Scanner"
    - "[FX=41] Lighthouse"
    - "[FX=42] Fireworks"
    - "[FX=43] Rain"
    - "[FX=44] Merry Christmas"
    - "[FX=45] Fire Flicker"
    - "[FX=46] Gradient"
    - "[FX=47] Loading"
    - "[FX=48] In Out"
    - "[FX=49] In In"
    - "[FX=50] Out Out"
    - "[FX=51] Out In"
    - "[FX=52] Circus"
    - "[FX=53] Halloween"
    - "[FX=54] Tri Chase"
    - "[FX=55] Tri Wipe"
    - "[FX=56] Tri Fade"
    - "[FX=57] Lightning"
    - "[FX=58] ICU"
    - "[FX=59] Multi Comet"
    - "[FX=60] Dual Scanner"
    - "[FX=61] Stream 2"
    - "[FX=62] Oscillate"
    - "[FX=63] Pride 2015"
    - "[FX=64] Juggle"
    - "[FX=65] Palette"
    - "[FX=66] Fire 2012"
    - "[FX=67] Colorwaves"
    - "[FX=68] BPM"
    - "[FX=69] Fill Noise"
    - "[FX=70] Noise 1"
    - "[FX=71] Noise 2"
    - "[FX=72] Noise 3"
    - "[FX=73] Noise 4"
    - "[FX=74] Colortwinkle"
    - "[FX=75] Lake"
    - "[FX=76] Meteor"
    - "[FX=77] Smooth Meteor"
    - "[FX=78] Railway"
    - "[FX=79] Ripple"
    - "[FX=80] Twinklefox"
    - "[FX=81] Twinklecat"
    - "[FX=82] Halloween Eyes"
  - platform: limitlessled
    bridges: 
      - host: 192.168.0.3
        groups: 
        - number: 1
          type: bridge-led
          name: Bedside
        
    
input_select:
  wled_presets:
    options:
      - "[PL=01] Preset 1"
      - "[PL=02] Preset 2"
      - "[PL=03] Preset 3"
      - "[PL=04] Preset 4"
      - "[PL=05] Preset 5"
      - "[PL=06] Preset 6"
      - "[PL=07] Preset 7"
      - "[PL=08] Preset 8"
      - "[PL=09] Preset 9"
      - "[PL=10] Preset 10"
      - "[PL=11] Preset 11"
      - "[PL=12] Preset 12"
      - "[PL=13] Preset 13"
      - "[PL=14] Preset 14"
      - "[PL=15] Preset 15"
      - "[PL=16] Preset 16"

  wled_palette_list:
    options:
      - "[FP=00] Default"
      - "[FP=01] Random Cycle"
      - "[FP=02] Primary color"
      - "[FP=03] Based on primary"
      - "[FP=04] Set colors"
      - "[FP=05] Based on set"
      - "[FP=06] Party"
      - "[FP=07] Cloud"
      - "[FP=08] Lava"
      - "[FP=09] Ocean"
      - "[FP=10] Forest"
      - "[FP=11] Rainbow"
      - "[FP=12] Rainbow bands"
      - "[FP=13] Sunset"
      - "[FP=14] Rivendell"
      - "[FP=15] Breeze"
      - "[FP=16] Red & Blue"
      - "[FP=17] Yellowout"
      - "[FP=18] Analoguous"
      - "[FP=19] Splash"
      - "[FP=20] Pastel"
      - "[FP=21] Sunset 2"
      - "[FP=22] Beech"
      - "[FP=23] Vintage"
      - "[FP=24] Departure"
      - "[FP=25] Landscape"
      - "[FP=26] Beach"
      - "[FP=27] Sherbet"
      - "[FP=28] Hult"
      - "[FP=29] Hult 64"
      - "[FP=30] Drywet"
      - "[FP=31] Jul"
      - "[FP=32] Grintage"
      - "[FP=33] Rewhi"
      - "[FP=34] Tertiary"
      - "[FP=35] Fire"
      - "[FP=36] Icefire"
      - "[FP=37] Cyane"
      - "[FP=38] Light Pink"
      - "[FP=39] Autumn"
      - "[FP=40] Magenta"
      - "[FP=41] Magred"
      - "[FP=42] Yelmag"
      - "[FP=43] Yelblu"
      - "[FP=44] Orange & Teal"
      - "[FP=45] Tiamat"
      - "[FP=46] April Night"
      - "[FP=47] Orangery"
      - "[FP=48] C9"
      - "[FP=49] Sakura"

input_number:
  ledspeed:
    name: Speed
    initial: 0
    min: 0
    max: 255
    step: 1
  ledintensity:
    name: Intensity
    initial: 0
    min: 0
    max: 255
    step: 1
input_boolean :
  wakeup_enabled:
    name: "Wake-up lights"
    initial: on
    icon: mdi:theme-light-dark
  wakeup_weekend:
    name: "Enable Wake-up on weekends"
    initial: off # I disable the system on default on weekends
    icon: mdi:calendar-blank
input_datetime:
  wakeup_time:
    name: "Start lights at"
    has_time: true
    has_date: false
homekit:
    filter:
        exclude_domains:
          - light
          - device_tracker
          - input_boolean
          - remote
          - script
          - alarm_control_panel
          - sensor
          - automation
          - media_player
          - binary_sensor
          - scene
          - person
          - switch
          - climate
        include_entities:
          - light.bedside
          - light.front
          - light.lamp
          - light.top
          - light.unit
          - light.wled
          - switch.achack
          - switch.power
          - switch.swing
          - switch.tv
          - media_player.kodi
          - sensor.dht_sensor_temperature
          - switch.ledfx
          - switch.milight_nightlight
    entity_config:
        media_player.kodi:
          feature_list:
            - feature: play_pause
            - feature: play_stop
            - feature: toggle_mute